### ISSUE TITLE
Display better error message if user tries to connect to the server with auth enabled but not configured in config.js

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2web#118]
We should display a better and more friendly error message, something along the lines of "This server requires authentication make sure it's configured properly in config.js".

![selection_162](https://cloud.githubusercontent.com/assets/125088/6732211/8fd09286-ce4a-11e4-8a4c-8f7e9e63c913.png)

**Comment by enykeev** [comment]
Agree. Server returning 401 is an easy error to handle. Still struggling to find a way to filter out CORS errors.

**Comment by Kami** [comment]
Confirmed the fix. Looking good. Thanks.
