### ISSUE TITLE
Display a better error message if user tries to authenticate with invalid credentials

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2web#119]
I believe this is a regression since IIRC, we did display "invalid credentials" message in the past. Now the login page just lets you through and you see the unfriendly error message.

![selection_163](https://cloud.githubusercontent.com/assets/125088/6732263/e5f40a9e-ce4a-11e4-9ed6-907c6e08fbe8.png)

**Comment by enykeev** [comment]
Wrong credentials should invoke https://github.com/StackStorm/st2web/blob/master/apps/st2-login/controller.js#L39 instead of allowing transition to `/history`. I'll check this out tomorrow.

**Comment by Kami** [comment]
Confirmed the fix. Looking good. Thanks.
