### ISSUE TITLE
Better presentation for errors

### ISSUE THREAD

**Issue by enykeev** [StackStorm/st2web#131]
We need a solid single way of presenting the long error messages or notifications for successfully performed background tasks. This especially important for rule editing flow since we may never be able to cover all the possible ways things may go wrong using just client-side validation.

Most obvious solution would be to use popup notification messages in the corner of the page, but I would prefer us to think of the other options first.

**Comment by enykeev** [comment]
@gmedrano I've assigned it to you for now since we need to figure out the UX side of it first. When you have a moment, take a look on how it is done now in rule flow (try to rename the rule with the name of another existing rule) in think on how we can improve on that and avoid sending user to the development console for the error message.

**Comment by emedvedev** [comment]
Solved by @alex-shnayder, and if we need an even better view, we can open a separate issue later.
