### ISSUE TITLE
Check Freshdesk feedback widget

### ISSUE THREAD

**Issue by enykeev** [StackStorm/st2web#132]
@jfryman proposed to take a look at Freshdesk feedback widget as a replacement for "Report a bug" link to Github issues.

http://freshdesk.com/customer-engagement/feedback-widget

**Comment by jfryman** [comment]
Would you try to just log into https://stackstorm.freshdesk.com with your StackStorm Google account. If that doesn't work, I'll create an account. It should do the needful.

**Comment by enykeev** [comment]
After some experimentation, I remember us left unsatisfied with the whole process of adding new user to admins.

@jfryman what have we decided, are we going to give freshdesk another try or should I close the issue?

**Comment by jfryman** [comment]
@enykeev I actually totally agree. I was really turned off by the apparent lack of integration with Google Apps, which was actually one of my draws to them based on their marketing. I'm not proceeding with them. 

Closing for now. Still would like to see something like this, but Freshdesk ain't it.
