### ISSUE TITLE
Rule page ain't show when it was last applied on a trigger. 

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2web#142]

**Comment by enykeev** [comment]
@lakshmi-kannan Dunno what you're talking about. Care to elaborate?

**Comment by emedvedev** [comment]
I'll just assume it's safe to close, seeing as the last comment is dated May 6 and says "dunno what you're talking about".

**Comment by manasdk** [comment]
I think it was mean to identify what was the last trigger-instance the rule applied to.

IMO we should probably expose that differently anyway.
