### ISSUE TITLE
Code hightlighter hangs on a particularly large snippets

### ISSUE THREAD

**Issue by enykeev** [StackStorm/st2web#161]
Due to the nature of `Prism.highlight`, it tends to block the whole thread until it finish tokenizing the string. While this is usually not that big of a problem, in some cases (ex., when st2 is used for CI/CD and dealing with exceptionally verbose output), it might result some browsers freezing on History tab of st2web.

To prevent highlighter from affecting performance of the rest of the app, we need to spawn the Tokenizer as web worker. Prism codebase already provides the solution for this task (https://github.com/PrismJS/prism/blob/gh-pages/prism.js#L201-L217) but it requires some changes to the production build pipeline.

As a long term solution for that kind of problems, we need to stop storing the results of the execution inside an execution itself instead create an additional model and API endpoint that would allow us to  stream the long output or its parts.

**Comment by Kami** [comment]
Yeah, using web workers sounds like a right thing to do.

As far as having a separate endpoint and streaming output goes - I also agree on that, we already have a RFC for that, we just need to implement it :)

**Comment by enykeev** [comment]
Ok, it seems like web worker by itself isn't going to help us too much. Yes, it solves main thread blocking, but now Chrome consumes all available CPU time on background trying to tokenize the code of the execution and the process only stops when the tab gets closed.

This very much seem to me like an infinite loop somewhere inside Prism's `tokenize` method. Strange enough, Safari is not affected by that problem and highlights the code successfully albeit still uncomfortably slow.

**Comment by Kami** [comment]
That's weird indeed. Maybe some bug which only affects V8?

In any case, we might implement some heuristics and only try to highlight the code if it passes some criteria (e.g. size < X and "looks like code").

**Comment by Kami** [comment]
We could also experimental by providing this functionality on the server (e.g. via a special "view" API endpoint) using pygments.

If we provide it on the server, we can also cache the highlighted version. It's obviously not ideal thought.

**Comment by dzimine** [comment]
+1 for (tokenize if size < X), a simple fix for now; and will work in practice - the outputs that kill st2 now are long CLIs, rarely long JSONs.

**Comment by enykeev** [comment]
That's what I did for `st2build001`, but I'm still hoping to find a better solution for the master.

**Comment by enykeev** [comment]
I believe this one is done and now the bottleneck is in downloading the code (an actual transmission time), but 'll need to profile to be sure.

**Comment by enykeev** [comment]
No new reports. Closing.
