### ISSUE TITLE
Stream and Execution endpoint report different time

### ISSUE THREAD

**Issue by enykeev** [StackStorm/st2web#166]
According to the report, the time of the execution is changing during page reload from `Jul 2, 2015 3:12:26 AM` to `Jul 1, 2015 11:12:26 PM`. Also, non of them reflect neither server local nor UTC time.

**Comment by enykeev** [comment]
Apparently, the bug was introduced sometime after 0.11.1 and was resolved in https://github.com/StackStorm/st2/pull/1630, though the fix has not been merged into 0.11 and only accessible in 0.12dev releases. For now, we don't have an ETA on when the changes would land in stable.

As for the scope, the bug is localized inside st2 and doesn't require any fixes on st2web side.

**Comment by Kami** [comment]
Fix is now also included in v011.6 - http://downloads.stackstorm.net/releases/st2/0.11.6/.
