### ISSUE TITLE
Strange behavior on Rules tab

### ISSUE THREAD

**Issue by armab** [StackStorm/st2web#177]
See the screenshot. Any action with `Rules` redirects back to default to `History` tab:

![st2webui-rules-bug](https://cloud.githubusercontent.com/assets/1533818/9084505/191774fc-3b7d-11e5-9f77-89e918b79b70.gif)
(click for full resolution)

st2 version is the most recent, installed with `st2_deploy.sh`:
```sh
# st2 --version
st2 ('0.13dev.159',)
```

**Comment by enykeev** [comment]
It has been fixed in #174. Make sure your st2web got properly updated too.

**Comment by armab** [comment]
I see.

Seems webui build is outdated in `latest` development branch:
https://downloads.stackstorm.net/releases/st2/0.13dev/ - `21-Jul-2015 22:01` for `webui`

**Comment by armab** [comment]
@manasdk @lakshmi-kannan is it possible to update https://downloads.stackstorm.net/releases/st2/0.13dev/webui/ build?

Because `webui` version in that archive contains bug users most probably won't understand :japanese_ogre:

**Comment by manasdk** [comment]
@armab Yes. I will figure out how to update.

**Comment by manasdk** [comment]
@armab Updated. For some strange reason the build was being published to 0.10dev. 

Anyway build is now published to the right bucket on download server.

**Comment by manasdk** [comment]
Fixed!

**Comment by armab** [comment]
Thanks @manasdk  :v:
