### ISSUE TITLE
Issue with rule edit

### ISSUE THREAD

**Issue by manasdk** [StackStorm/st2web#183]
While creating the rule in the UI, we probably spotted some wrong behavior: Try to create a criteria based on the slack channel name (trigger.channel.name). While it is possible to do that during rule creation, the save button will be disabled if you ever want to edit the rule again and do not delete the criteria referring to trigger.channel.name again:

```
"criteria": {
    "trigger.text": {
      "pattern": "^Comment on <https://github\\.com/.*$",
      "type": "matchregex"
    },
    "trigger.channel.name": {
      "type": "contains",
      "pattern": "git"
    }
  },
 ```

Note : report came in via support

**Comment by jonico** [comment]
The suggestion box in StackStorm does not show any nested attribute of trigger.channel, I guess this is related to the same root cause

**Comment by emedvedev** [comment]
@jonico Same as #184—you can expect some progress later this week. :) Thanks a lot for reporting!
