### ISSUE TITLE
Action param type and rule param type mismatch may be an issue

### ISSUE THREAD

**Issue by manasdk** [StackStorm/st2web#184]
I am using the StackStorm UI to design my rules. Whereas in the UI I can see the expression in the issue field, the JSON I just pasted says null. This is probably because issue is an int field in the JSON.

created rule - 
```
{
  "name": "CommentOnGitHubPullRequest",
  "tags": [],
  "enabled": true,
  "trigger": {
    "type": "slack.message",
    "parameters": {},
    "pack": "slack"
  },
  "criteria": {
    "trigger.text": {
      "pattern": "^Comment on <https://github\\.com/.*$",
      "type": "matchregex"
    }
  },
  "action": {
    "ref": "github.add_comment",
    "parameters": {
      "body": "{{trigger.text | regex_replace(\"(^Comment on <https://github\\.com/[^/]*/[^/]*/pull/)|(>:[^:]*$)\", \"\") | int(35)}}",
      "repo": "{{trigger.text | regex_replace(\"(^Comment on <https://github\\.com/[^/]*/)|(/pull/[^/]*>:[^:]*$)\", \"\")}}",
      "issue": null,
      "user": "{{trigger.text | regex_replace(\"(^Comment on <https://github\\.com/)|(/[^/]*/pull/[^/]*>:[^:]*$)\", \"\")}}"
    }
  },
  "ref": "default.CommentOnGitHubPullRequest",
  "id": "55d64316c0f3143f8fe4ff16",
  "pack": "default"
}
```

**Comment by jonico** [comment]
I shall mention that the expression used for the issue parameter was exactly the same as for body (where it worked without problems). Even though the JSON view shows null for issue, hitting save in the StackStorm UI saved the expression for the issue parameter and loads it correctly whenever I edit the rule again.

**Comment by emedvedev** [comment]
@jonico I'm going to look into it in the next few days and will keep you posted.

**Comment by emedvedev** [comment]
@jonico We made a slight change to `github` pack in [st2contrib](https://github.com/StackStorm/st2contrib) to allow strings in the "issue" field. You'll have to reinstall the pack in StackStorm, and then everything should be fine.

cc @manasdk

**Comment by jonico** [comment]
Awesome, I just did
! pack deploy github
(in slack using Hubot)

and it started to work.

Will there be any core change to allow Jinja templates for int parameters or is the lesson learned that one should not have int typed parameter for that very reason?
