### ISSUE TITLE
After AWS installation (ami-de454e8c) with errors, cannot AUTH: Unable to reach auth service. [auth:https://:9100]

### ISSUE THREAD

**Issue by NicolasMas** [StackStorm/st2web#211]
Error message on 

`Unable to reach auth service. [auth:https://:9100]`

![image](https://cloud.githubusercontent.com/assets/1871481/9709031/f726234a-5556-11e5-953d-fbb753257272.png)

**Comment by armab** [comment]
@NicolasMas do you have more details on this? It's hard to say without more info.

Have you tried to navigate manually `https://host:9100/` ?
Maybe related to self-signed certificates.
Also `sudo st2ctl status` might help to investigate it.

Thanks.

**Comment by NicolasMas** [comment]
Done everything you mentioned. Does not work. I am using a fresh AMI without changing anything, so I am not sure I can provide more input. You should probably able to reproduce it with self signed certificates.

**Comment by dzimine** [comment]
Nicolas, sorry for the trouble with installer. We are seeing it with some other folks, but can't repro it unfortunately just yet. 

There are two cases 1) WebUI doesn't work and 2) nothing, even local CLI `st2 auth` doesn't work. I assume you're case 2, right? 

We have a lead on the problem. If you pop up on stackstorm-community.slack.com ([registration here](https://stackstorm.typeform.com/to/K76GRP)) you can follow the troubleshooting thread there. Else we'll keep you posted here. cc @jfryman.

**Comment by Heshuge** [comment]
I'm getting the same issue. It is legit.

**Comment by NicolasMas** [comment]
K. I had that on Chrome, OSX Yosemite.

**Comment by Heshuge** [comment]
I found a workaround by manually navigating to ports 9100, 9101 and confirming the security certs.

**Comment by emedvedev** [comment]
Closing as this is fixed by single-port deployment, and the AMI is deprecated in favor of all-in-one installer.
