### ISSUE TITLE
Invalid error message returned on invalid credentials

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2web#227]
It looks like there was a regression since if the auth service is online and you enter invalid credentials you get the following error back "Unable to reach auth service. [auth:https://:9100]".

Entering correct credentials works fine.

![selection_234](https://cloud.githubusercontent.com/assets/125088/10022828/1f4b4996-614f-11e5-9c4a-cce9a923fb25.png)

On a related note - this (grey?) font color in the error bubble is hard to read on this backround. Should probably change it.

**Comment by emedvedev** [comment]
Resolved.
https://www.dropbox.com/s/zoye4hhembskqx3/Screenshot%202015-12-18%2007.03.54.png?dl=0
