### ISSUE TITLE
Cancel Button

### ISSUE THREAD

**Issue by outcast** [StackStorm/st2web#240]
It is great that we have a Rerun button now but a Cancel button would be awesome too!

**Comment by enykeev** [comment]
Thanks for report! Just to confirm, are you talking about the button that would allow you to stop execution in the middle of the process?

**Comment by outcast** [comment]
That is correct.

**Comment by outcast** [comment]
@enykeev anymore movement on this?

**Comment by enykeev** [comment]
@outcast sorry for the delay, just got back from the vacation. I've put together a PR for this change (see #268). I haven't talked with the team yet so I can't say when this change will go live, though.

**Comment by outcast** [comment]
@emedvedev did this get implemented?

**Comment by emedvedev** [comment]
@outcast: Yes, https://github.com/StackStorm/st2web/pull/268 is merged. Sorry, should've notified you before closing, just assumed you were following the PR as well :)
