### ISSUE TITLE
Feature request: parameters order the same way they are defined in meta

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2web#274]
Hello,

It would be nice to order parameters in the WebUI the same way they are defined in meta files. Perhaps, adding an optional `order` field to the parameters in the meta would let it implement easier.

Thanks!

**Comment by armab** [comment]
Duplicate of https://github.com/StackStorm/st2web/issues/154

**Comment by Kami** [comment]
Closing because it's a duplicate.

Let's please continue in #154 - thanks!
