### ISSUE TITLE
[Possible bug] CORS operation respect, support client url (same as location.hostnome)

### ISSUE THREAD

**Issue by dennybaa** [StackStorm/st2web#290]
There seems to be an issue on configurations where webui operates behind NAT. Reproduce.
1. Bring up st2web under vagrant. Required vagrant config is:
   
   ```
   config.vm.network "forwarded_port", guest: 80, host: 8080
   config.vm.network "forwarded_port", guest: 443, host: 8443
   ```
   
   Network mode should be NAT (forward), not bridged!

Connect to `https://localhost:8443` on the host node and try to login with console open. Requests do not regard correct `proto+hostname` part which is `https://localhost`, but it actually should be equal to the one on client side (location.hostname or whatever). So for example `/auth/tokens` method of course fail.

```
Request URL:https://localhost/auth/tokens
Request Headers
Provisional headers are shown
Access-Control-Request-Headers:accept, authorization
Access-Control-Request-Method:POST
Origin:https://localhost:8443
Referer:https://localhost:8443/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/48.0.2564.82 Chrome/48.0.2564.82 Safari/537.36
```

However `config.js` can not be used to change the paths for these kind of requests (_client-side_), because server side requests are relative to the server (where endpoints can be reached as `https://localhost/smth` or whatever is in `config.js`) at the same point client side requests **should not use the same** endpoint address, but rather use _hostname_ part available from the client.

cc: @enykeev

**Comment by enykeev** [comment]
I had very hard time understanding the point of this issue when if was initially filled and the time didn't help either.

As far as I can tell, CORS behaves correctly in this case. Thing you need to keep in mind when dealing with the CORS is that it it revolves around what browser perceive as Origin, not the server. If you type `https://localhost:8443/` in browser address bar, this is what origin is going to be no matter how many different proxies you have in between. Also, keep in mind that origin is not `proto+hostname`, but `proto+hostname+port`.

Going to close it for now considering this doesn't look like a bug to me. Feel free to reopen.
