### ISSUE TITLE
Config variable for st2stream

### ISSUE THREAD

**Issue by enykeev** [StackStorm/st2web#299]
Since we've yet to deprecate direct access to services, we need to make sure user has an ability to access st2stream directly too. Example config:

```
hosts: [{
  name: 'Dev Env',
  url: '//172.168.50.50:9101',
  auth: '//172.168.50.50:9100',
  stream: '//172.168.50.50:9102'
}]
```

**Comment by enykeev** [comment]
I don't remember hearing anything about that from our users. There is a good possibility that the whole config.js is no longer relevant now that we have nginx as a part of reference deployment.

**Comment by christopherjbaker** [comment]
@enykeev Does this still apply?

**Comment by enykeev** [comment]
apparently it does

**Comment by LindsayHill** [comment]
Addressed by https://github.com/StackStorm/st2web/pull/525/commits/a85348cbc4512b3c24c482915155f42a0e32c97c, part of https://github.com/StackStorm/st2web/pull/525
