### ISSUE TITLE
Other color for cancel button

### ISSUE THREAD

**Issue by johandahlberg** [StackStorm/st2web#310]
Canceled workflows are displayed in a grey color very similar to the oscillating grey for running workflows. To make the two easier to distinguish between I'd suggest displaying it in a different color. Perhaps yellow to sync with what is displayed in the CLI? I can see if this is not high up on the priority list, but I just thought I'd mention it.

Keep up the good work!

**Comment by enykeev** [comment]
Resolved in https://github.com/StackStorm/st2web/pull/316

**Comment by johandahlberg** [comment]
Awesome!
