### ISSUE TITLE
On gulp, get object is not a function for zlib.js callback function

### ISSUE THREAD

**Issue by m4dcoder** [StackStorm/st2web#311]
zlib.js:167
    callback(null, buf);
    ^
TypeError: object is not a function
    at Gzip.onEnd (zlib.js:167:5)
    at Gzip.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:458:13)

**Comment by enykeev** [comment]
Since `zlib.js` is a part of node itself, I'm assuming you've been using an old version of node. We're using 4.2.2 in circleci environment (https://github.com/StackStorm/st2web/blob/master/circle.yml#L8). Should probably update readme and package.json to reflect that.

**Comment by elijah** [comment]
node:6.9.4-slim works pretty well with st2web, it seems.  newer (7.x.x series) seems to get sad about an internal/fs interface that has changed.  I just rewired someone else's contribution to build a container, here:  https://github.com/elijah/docker-st2web

**Comment by christopherjbaker** [comment]
This has been fixed in the [react rewrite](https://github.com/StackStorm/st2web/pull/420), which should be included with 2.6.
