### ISSUE TITLE
long lines when viewing action output or code tab

### ISSUE THREAD

**Issue by JohnWelborn** [StackStorm/st2web#329]
Long lines when viewing action output or on the code tab require either lots of scrolling or pasting into something that can provide line wrap and as a bonus, process the newlines for readability.

It is still very valuable to be able to copy the output in part or whole into python, but adding line wrap would make it more readable and still allow this copy/paste.

Unless there are plans to replace this interface with more of a form, an idea for handing strings with a lot of lines would be to convert:
{'test': 'this is line one\nthis is line two'}
to this:
{'test': 'this is line one\n'
         'this is line two'}
(if only pprint had this as an option)

**Comment by leleSahil** [comment]
@JohnWelborn @enykeev Do you know if this extended functionality is being worked on or is planned for a future release? My team would find this enhancement extremely helpful and is interested in pursuing such a fix

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/community/p1492119887436441

**Comment by LindsayHill** [comment]
Closed, thanks to the super contribution from @leleSahil in #351
