### ISSUE TITLE
YAML dumper produces invalid rule code

### ISSUE THREAD

**Issue by enykeev** [StackStorm/st2web#336]
YAML representation of the rule code created by translating json version to yaml is not valid from the point of view of RuleRegistrar module.

```
trigger:
  ...
criteria:
action:
  ...
```
gets translated back to json as

```
"trigger": ...,
"criteria": null,
"action": ...
```
 and then tries to parse over the criteria field without any additional validation which results in an exception.

**Comment by christopherjbaker** [comment]
@enykeev Is this a frontend bug? If so, does it persist in the rewrite?

**Comment by LindsayHill** [comment]
As far as I can tell, this is no longer relevant.
