### ISSUE TITLE
{BWC 2.1.1 } Unable to access the GUI when installed on Centos-7.2 . ISO Image --> CentOS-7-x86_64-Minimal-1611

### ISSUE THREAD

**Issue by uday83** [StackStorm/st2web#348]
1. Installed Stack Storm with DC-FABRIC suite on Centos 7.2. 
2. st2 and pack installation was successful
3. GUI doesnt open/work

ISO Image --> CentOS-7-x86_64-Minimal-1611. Couldnt attach the file as the size is > 10MB

Attaching the installation logs

[bwc-topology-db.txt](https://github.com/StackStorm/st2web/files/741282/bwc-topology-db.txt)
[bwc-topology-service.txt](https://github.com/StackStorm/st2web/files/741283/bwc-topology-service.txt)

**Comment by LindsayHill** [comment]
Have asked for additional info on Slack

**Comment by uday83** [comment]
I see this ERR_CONNECTION_TIMED_OUT message on web page . 

[root@localhost uday]# sudo netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:9100          0.0.0.0:*               LISTEN      1042/python
tcp        0      0 127.0.0.1:9101          0.0.0.0:*               LISTEN      1005/python
tcp        0      0 127.0.0.1:9102          0.0.0.0:*               LISTEN      1038/python
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1077/nginx: master
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      1147/epmd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1082/sshd
tcp        0      0 127.0.0.1:8888          0.0.0.0:*               LISTEN      1008/python
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1145/postgres
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1916/master
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      1077/nginx: master
tcp        0      0 127.0.0.1:8989          0.0.0.0:*               LISTEN      1003/python
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      1047/beam
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      1279/mongod
tcp6       0      0 :::4369                 :::*                    LISTEN      1147/epmd
tcp6       0      0 :::22                   :::*                    LISTEN      1082/sshd
tcp6       0      0 ::1:5432                :::*                    LISTEN      1145/postgres
tcp6       0      0 ::1:25                  :::*                    LISTEN      1916/master
tcp6       0      0 :::5672                 :::*                    LISTEN      1047/beam
[root@localhost uday]# ip addr

**Comment by LindsayHill** [comment]
ST2 is running OK, and the webserver (nginx) is listening on port 80 & 443.

So now it's just a straightforward troubleshooting exercise (i.e. It's not
specific to ST2, this is the same steps for any application)

Are you running a local firewall on that system?

Are you connecting to the right IP address?

Is this a Virtualbox VM, or a remote ESXi VM?

**Comment by LindsayHill** [comment]
Will deal with this via Slack, since it's not an ST2 issue, but seems to be system-level problem
