### ISSUE TITLE
API does not prevent spaces in rule names, and chokes when there are % encoded spaces.

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/st2web#357]
I tried creating a simple rule from the webui: IF core.st2.DateTimer THEN examples.hello. When I did, it jumped to the history with this error message:

> Failed to update list
> Cannot read property 'getRef' of null

Going back to rules, I can click on the notify and the example monitor_file rules, but if I click on my "Timer Test" rule, it takes me back to the history view.

From the CLI, I can see that the rule was created:
```
root@e96ff2f68a98:/opt/stackstorm# st2 timer list
+--------------------------+------+-----------------------+--------------------+-----------------------+
| id                       | pack | name                  | type               | parameters            |
+--------------------------+------+-----------------------+--------------------+-----------------------+
| 592305f225e008010c9615a8 | core | 93eab0fb-66b9-49ae-   | core.st2.DateTimer | {u'date': u'2017-05-2 |
|                          |      | b4cd-2e33acdbc6d1     |                    | 2T15:37:45,567070033+ |
|                          |      |                       |                    | 0000'}                |
+--------------------------+------+-----------------------+--------------------+-----------------------+
...
root@e96ff2f68a98:/opt/stackstorm# st2 rule list   
+-----------------------+----------+-----------------------------------+---------+
| ref                   | pack     | description                       | enabled |
+-----------------------+----------+-----------------------------------+---------+
| chatops.notify        | chatops  | Notification rule to send results | True    |
|                       |          | of action executions to stream    |         |
|                       |          | for chatops                       |         |
| examples.monitor_file | examples | Monitor file for change           | True    |
| test.Timer Test       | test     | timer test                        | True    |
+-----------------------+----------+-----------------------------------+---------+
```

Though I couldn't do anything with the rule from the WebUI, I was able to delete it in the CLI:
```
root@e96ff2f68a98:/opt/stackstorm# st2 rule delete "test.Timer Test"
Resource with id "test.Timer Test" has been successfully deleted.
```

Please add some validation to the rule name field so that it doesn't have spaces, or make it handle spaces more gracefully.

**Comment by bigmstone** [comment]
So digging into this it appears that it's not just a problem w/ WebUI, but rather a problem with ST2 API. When you create a rule via WebUI or even CLI the name of the rule is submitted in the post body. When you go to modify, delete, or use the rule in the webui or CLI it is part of the URI which includes a `%20` for the space. The `%20` is not interpreted correctly on the far end and it looks for a rule named `my%20action%20with%20a%20space` which is obviously not found. So I'm working on a fix and will use this issue to track it.

**Comment by ahubl-mz** [comment]
@cognifloyd, @christopherjbaker Please reopen this. This should ultimately be fixed in the API (to not allow rules with spaces in the name), but this can be helped in the UI by validating the name field with a regex that disallows spaces and any other characters that aren't allowed in rule names.
