### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by DesignByOnyx** [StackStorm/st2web#366]
After about a day of having the Brocade UI open in Chrome, I received a system warning similar to the following (note: not an exact screenshot from my machine - grabbed it from google):

![image](https://user-images.githubusercontent.com/514040/27455804-d0d0c39a-575b-11e7-84f4-d3e81ad1f737.png)

I wasn't sure this was related to StackStorm, but another user (@emptywee) just reported that he had "run out of memory" with the History tab open for 1 day. I too had the History tab open when I received the system error above. I will try and investigate further to help save you guys some time.

**Comment by DesignByOnyx** [comment]
Observation 1: switching tabs while data is loading results in reference errors:

![image](https://user-images.githubusercontent.com/514040/27457639-bebdedb6-5762-11e7-998a-b4de0f020789.png)

To reproduce:
- Click on 'Actions' tab
- Wait for loading icon
- Switch to 'History' tab
- Notice error

I wasn't trying to investigate this issue yet, but this happens quite frequently as I quick click through the app.

**Comment by emptywee** [comment]
Yeah, I agree, it looks like it's bloating and swelling over time:

![image](https://user-images.githubusercontent.com/4997180/27458541-27360a84-576f-11e7-9560-16d650897760.png)

**Comment by DesignByOnyx** [comment]
I'm not sure if this is related, but @mickmcgrath13 and I are on the same team and I am just trying to give you guys as much information as possible. He was experience orphaned data on the server side (see [this issue](https://github.com/StackStorm/st2/issues/3506)). Could be related as there seem to be some real-time (socket) updates going on and... well, just a thought.

I've also been keeping my Chrome task manager open and keeping an eye on the memory usage and it seems to be stable (for several hours now). I'll report back if I notice anyting (not doing any head snapshots or anything until I notice a leak).

**Comment by bigmstone** [comment]
@DesignByOnyx I'd say create a separate issue for the `getRef` of null issue. This is likely a race in some of the async calls happening when the react elements are being created, but it should be largely only cosmetic.

**Comment by DesignByOnyx** [comment]
Update: I have kept tabs open for days (almost a week) and have not been able to reproduce the memory leak. Our server was restarted several times during this period. Afaik this was a fluke of a situation. Closing for now and will reopen if I can cause it to happen again.
