### ISSUE TITLE
Action parameter order must be as per the 'position' attribute for both GUI and CLI

### ISSUE THREAD

**Issue by ramgolla** [StackStorm/st2web#367]
Position field is used to specify parameter order in actions until https://github.com/StackStorm/st2web/pull/363 in 2.3.  

If the position field is populated in the metadata,  it must take the precedence for both CLI and UI.

**Comment by armab** [comment]
From @LindsayHill https://github.com/StackStorm/discussions/issues/244#issuecomment-313582167 clarifying comment:


> It was doing it by positional parameters previously. I think the ordering needs to go to something like:
>- Positional
>- Required
>- Alphabetical

:+1:
