### ISSUE TITLE
Feature Request: Trigger event history

### ISSUE THREAD

**Issue by johnarnold** [StackStorm/st2web#369]
Would be really useful to have a dashboard, similar to the actions history, that displays all the trigger events that have been emitted by all the sensors, ideally with a way to filter by sensor, and drill down to see all the event fields.

**Comment by Kami** [comment]
Agreed :+1:

**Comment by christopherjbaker** [comment]
Is this information currently available via the API? or would we need to add that to the backend first?

**Comment by cognifloyd** [comment]
https://api.stackstorm.com/api/v1/triggerinstances/

**Comment by LindsayHill** [comment]
Added in master, will be released (shortly) in 2.8
