### ISSUE TITLE
CI Should fail on Lint Errors

### ISSUE THREAD

**Issue by bigmstone** [StackStorm/st2web#381]
If CI throws a lint error it should fail. It currently passes. This is primarily for my PRs. 😄

**Comment by enykeev** [comment]
Yeah, I've noticed some linting errors, but was myself under the impression they are failing. I'll take a look today, there's something in `gulp` that prevents that.

**Comment by bigmstone** [comment]
@enykeev I clean up those linting issues in #377

**Comment by christopherjbaker** [comment]
This has been fixed in the [react rewrite](https://github.com/StackStorm/st2web/pull/420), which should be included with 2.6.
