### ISSUE TITLE
Drop-down / combobox fields

### ISSUE THREAD

**Issue by vincent-legoll** [StackStorm/st2web#383]
It would be really cool if the UI could have drop down (comboboxes) for string fields.

You will then be allowed to choose one item from a specified list without having to know in advance what is allowed in the field. And it will also require no keyboard typing.

(not sure if underlying st2 / API would need changes for that)

**Comment by bigmstone** [comment]
@vincent-legoll I believe what you're looking for is `enum` parameter type. This will allow you to specify a list of options for a parameter and this is rendered as a drop-down in st2web. [Here](https://github.com/StackStorm/st2/blob/master/contrib/examples/actions/mistral-branching.yaml#L11) is an example usage from one of our example actions.

I will close this for now, but feel free to open this issue again if I mis-interpreted your request.

**Comment by vincent-legoll** [comment]
OK cool, looks like what I want.

BTW, I tried to search for it before creating this issue, so you should maybe add something about it there:
https://docs.stackstorm.com/actions.html#action-metadata

An example (or a link to one, like what you gave above) would be nice.

Because even my google searches returned nothing...
