### ISSUE TITLE
Remember wrap lines & show newlines buttons states

### ISSUE THREAD

**Issue by vincent-legoll** [StackStorm/st2web#391]
Those buttons are very useful, but their state is not saved.

What I would like is: when one of those options is activated in an action instance's detailed view, it is kept in that state, even if I close the details view and open another one (for another action instance).

Like a global, per user, setting.

**Comment by christopherjbaker** [comment]
This has been fixed in the [react rewrite](https://github.com/StackStorm/st2web/pull/420), which should be included with 2.6, though this feature may not be included with the initial release.

**Comment by vincent-legoll** [comment]
Looks like this one is fixed in latest version, thanks
