### ISSUE TITLE
User input format for Array type parameters has changed in GUI

### ISSUE THREAD

**Issue by ramgolla** [StackStorm/st2web#394]
In BWC 2.3.2 GUI requires [ ] and " " when entering values for attributes of type Array.  Previously for interface name attribute user could give: 4/0/1, 5/0/1 but 2.3.2 version requires input as ["4/0/1", "5/0/1"].  

This sudden change seem to have been made to support complex objects as input.  However, this change makes it hard for everyone.  Users who need to input complex objects may not mind the new format, but it is very burdensome for many users of simple array.

**Recommendation:**
Please introduce a new type for complex objects, leave the simple array as before.

There are also some inconsistencies in the current implementation:

- Re-run of a workflow doesn't expect [ ] "".

- CLI doesn't expect []

This issue caused lot of confusion at T-Systems.

**Comment by dzimine** [comment]
Agreed on supporting both ways in UI: `1,2,3` and `[1,2,3]` as well as `[{foo:1},{bar:2}]`

PR that introduced the change: https://github.com/StackStorm/st2web/pull/360/files
