### ISSUE TITLE
Packs UI not displaying correctly on Safari

### ISSUE THREAD

**Issue by m4dcoder** [StackStorm/st2web#403]
On Safari, when at the Packs UI, the page don't expand properly. I only see about 1 inch of the page.

**Comment by Mierdin** [comment]
Yup, same for me

<img width="1440" alt="screenshot 2017-08-21 13 11 28" src="https://user-images.githubusercontent.com/4230395/29536367-62c3c80c-8672-11e7-9050-48c94bc2f3c8.png">
