### ISSUE TITLE
Clicking on some of the installed packs in pack UI doesn't show the pack info

### ISSUE THREAD

**Issue by humblearner** [StackStorm/st2web#405]
and gives following error:

![image](https://user-images.githubusercontent.com/11877841/29535863-64d261f0-8670-11e7-800a-9b48fd4ab277.png)

Note: aws pack is installed: 

```
vagrant@st2test:~$ st2 pack list
+----------+----------+---------------------------+---------+------------------+
| ref      | name     | description               | version | author           |
+----------+----------+---------------------------+---------+------------------+
| asserts  | asserts  | Exposes functions that    | 0.1.0   | Lakshmi Kannan   |
|          |          | can be used in tests for  |         |                  |
|          |          | assertion.                |         |                  |
| aws      | aws      | st2 content pack          | 1.0.0   | StackStorm, Inc. |
|          |          | containing Amazon Web     |         |                  |
```

including packs like: examples, fixtures.

**Comment by enykeev** [comment]
I'm failing to reproduce this issue https://cl.ly/3F3A2d1y3Q3A. Could you try again and provide more details?

**Comment by humblearner** [comment]
Steps To Reproduce:
1. Install couple of packs including `examples` pack.
2. Enter config for any pack, click `preview` and then `save` the config.
3. Click on other packs, these packs may not be selected and there is error in console:

![image](https://user-images.githubusercontent.com/11877841/29589888-12e3c668-874c-11e7-9929-1b86bcf8e998.png)

**Comment by enykeev** [comment]
Oh, I see. So the problem is caused by preview thing being open while switching between packs.
