### ISSUE TITLE
Minor: Update the error message to point to history tab instead of developer console.

### ISSUE THREAD

**Issue by humblearner** [StackStorm/st2web#410]
Instead of `See details in developer tools console.`, https://github.com/StackStorm/st2web/blob/28e879a4cc9099469d955f2d48f6cc16735b2e3e/apps/st2-packs/packs-panel.component.js#L94

Can we point to the `history` page for more details, maybe with execution ID?

![image](https://user-images.githubusercontent.com/11877841/29589284-9160c142-8749-11e7-8ed6-722b4f14af62.png)
 
as the error is hidden 
![image](https://user-images.githubusercontent.com/11877841/29589463-329a2058-874a-11e7-8f86-95c172379927.png)

and not as clean as the show on the history page:
![image](https://user-images.githubusercontent.com/11877841/29589558-8bf3cb72-874a-11e7-851f-297d129ba4ca.png)

**Comment by Kami** [comment]
Yeah, ideally we could like to the specific execution in the history entry.

Would be more friendlier.

**Comment by christopherjbaker** [comment]
This has been fixed in the [react rewrite](https://github.com/StackStorm/st2web/pull/420), which should be included with 2.6, though this feature may not be included with the initial release.
