### ISSUE TITLE
Workflow and status icon alignment on the History tab needs to be fixed

### ISSUE THREAD

**Issue by samirsss** [StackStorm/st2web#414]
The alignment of the status icon for workflows is out of sync with the status for individual actions in the history tab. This seems to be something recent. I am on the latest 2.4 builds for ST2

![screen shot 2017-08-23 at 9 31 21 am](https://user-images.githubusercontent.com/7357878/29627152-f36dd3d8-87e5-11e7-856e-352590e1043a.png)

**Comment by vincent-legoll** [comment]
I'm on 2.4.1 / centos7 and don't see that.

My workflows' status icons are at the same place as they are for single actions 

Maybe it has been fixed.

**Comment by armab** [comment]
It also makes sense mentioning the browser and its version to have instructions to reproduce the bug.

**Comment by christopherjbaker** [comment]
This has been fixed in the [react rewrite](https://github.com/StackStorm/st2web/pull/420), which should be included with 2.6.
