### ISSUE TITLE
Always show "show more" in action output, code, etc.

### ISSUE THREAD

**Issue by dzimine** [StackStorm/st2web#418]
Especially in "action output".
If there is a single long line with trace stack, I could handle it in full-string view but there's no "show more" button to open it in pop-up.

**Comment by LindsayHill** [comment]
+1 for this. Output is really annoying to display otherwise. Easy to miss the horizontal scroll bar.

**Comment by christopherjbaker** [comment]
This has been fixed in the [react rewrite](https://github.com/StackStorm/st2web/pull/420), which should be included with 2.6, though this feature may not be included with the initial release.
