### ISSUE TITLE
Web UI 2.4 input validation error for non-required inputs

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2web#424]
(copied from original logged by @DavidJohnGee at https://github.com/StackStorm/st2/issues/3741)

There is an issue with the Web UI on 2.4.

In rules or actions, If I input a value in a non-required form field then remove the value, I receive a validation error.

![image](https://user-images.githubusercontent.com/4283339/30378926-bd4db234-988c-11e7-89b5-b78b09281fc0.png)

![image](https://user-images.githubusercontent.com/4283339/30378943-ccd63bf4-988c-11e7-87dd-7dd3661e7613.png)

**Comment by christopherjbaker** [comment]
This has been fixed in the [react rewrite](https://github.com/StackStorm/st2web/pull/420), which should be included with 2.6.
