### ISSUE TITLE
Allow disabling the UI's changing items 

### ISSUE THREAD

**Issue by vincent-legoll** [StackStorm/st2web#429]
The always changing UI items in the history page consume too much CPU and that makes my speakers output some noise and makes the CPU cooler spin high.

When there is something changing in the history list left pane *OR* in the history details right pane (grey status icons for running actions) the CPU usage of firefox goes up. Up to 70% of a core on an core i5.

If FF is iconified or switched to another tab, the issues disappear. But not if FF is only obscured by another window, or if the panes are scrolled so that the spinner UI elements are off screen.

This is a really annoying issue.

FF ESR 52.4.0 (64-bit)
Debian stable 9.1x86_64
st2 & st2web 2.4.1 on centos 7 x86_64

**Comment by enykeev** [comment]
There's a decent chance the problem will go away after we finally switch to react. One of the temporary hacks might be to block /stream endpoint on your ad blocker of choice.

**Comment by christopherjbaker** [comment]
This should be fixed in the [react rewrite](https://github.com/StackStorm/st2web/pull/420), which should be included with 2.6.
