### ISSUE TITLE
Wrong parameters in re-run

### ISSUE THREAD

**Issue by vincent-legoll** [StackStorm/st2web#432]
When using re-run from the webui the parameters used to fill the form are not the ones that were used for that execution.

And in addition to that, if you change one of the wrong param to what you really wants, your modification is not taken to launch the new execution.

But re-running from the CLI is OK.

st2 version 2.5.0

**Comment by armab** [comment]
Thanks for the report!
Confirming the wrong behavior.

Related to https://github.com/StackStorm/st2web/issues/421 where checkbox gets lost when pushing the re-run button.

**Comment by vincent-legoll** [comment]
In don't have checkboxes for my actions, but had the bug for simple text fields & text fields with enums.

But I think this is the same bug.

**Comment by christopherjbaker** [comment]
This has been fixed in the [react rewrite](https://github.com/StackStorm/st2web/pull/420), which should be included with 2.6.
