### ISSUE TITLE
Add a link to "opened stdout / stderr popup window"

### ISSUE THREAD

**Issue by vincent-legoll** [StackStorm/st2web#434]
ER: It would be cool to have a link somewhere that would directly open the stdout / stderr popup window of an execution in history. I'd use this from a slack message so that people interested in the thing will get directly to the thing...

**Comment by christopherjbaker** [comment]
This has been fixed in the [react rewrite](https://github.com/StackStorm/st2web/pull/420), which should be included with 2.6, though this feature may not be included with the initial release.
