### ISSUE TITLE
Misleading navigation button captions in history view

### ISSUE THREAD

**Issue by vincent-legoll** [StackStorm/st2web#437]
When in history view, the data is date/time-ordered, but the navigation buttons are labelled "previous" & "next", which is backwards as it represents a previous/next-page-of-results.

Either the buttons should swap actions, i.e. previous goes to next-result-page, or the label should better reflect what they're going to do, like "previous page" or something less misleading.

My preference would to just swap the action.

**Comment by enykeev** [comment]
Thanks for the report, that’s a nice catch.

I think we should rename the buttons to Earlier and Later for History app.

**Comment by vincent-legoll** [comment]
I like the "newer" & "older"... Closing as fixed !
