### ISSUE TITLE
colorblind support

### ISSUE THREAD

**Issue by Carles-Figuerola** [StackStorm/st2web#439]
On some screens or setups it might be fairly difficult for colorblind people (myself included in this example) to see the difference between the green/red success status dot. Changing the colors to a more contrastful tones of green/red would be helpful but maybe adding an icon in the middle of the dot would be ideal:
![image](https://user-images.githubusercontent.com/13749641/33963145-8c1e8240-e019-11e7-8e2c-d73e4eb492e1.png)

This second option might be detrimental to screen readers, but maybe a middle ground could be found.

**Comment by LindsayHill** [comment]
This is still needed for 2.8. It has not yet been merged.

**Comment by LindsayHill** [comment]
Improvements added to 2.8 in https://github.com/StackStorm/st2web/commit/68de4b8b4e0af1591b5a736414389677bdbc7bed and https://github.com/StackStorm/st2web/commit/2a25987fd5339bd698b67925c41edeaef7e3baa8
