### ISSUE TITLE
react-dev: error when going back from code to general tab in an action in action-chain

### ISSUE THREAD

**Issue by humblearner** [StackStorm/st2web#443]
- Select an action in action chain
- Goto code tab in the sidebar
- Click on the general tab:
![image](https://user-images.githubusercontent.com/11877841/34016684-adfb4dbc-e0d7-11e7-9da0-db8b1c9abf83.png)

The details in general tab are from code tab.

**Comment by christopherjbaker** [comment]
I did a fair amount of refactoring that affected this, though I did not deliberately fix it. I cannot recreate it at the moment, however, even using a "register pack" execution inside a "packs.install".
