### ISSUE TITLE
react-dev: User defined rule creation and selection has couple of issues

### ISSUE THREAD

**Issue by humblearner** [StackStorm/st2web#448]
User Defined rule has few errors.

Select user defined rule:
![image](https://user-images.githubusercontent.com/11877841/34022087-0f0663c0-e0f2-11e7-94c7-84cf5ecab6d6.png)

Make changes to the user defined rule:
![image](https://user-images.githubusercontent.com/11877841/34022106-35c579ce-e0f2-11e7-9c84-4819afa29e55.png)

**Comment by christopherjbaker** [comment]
I did a fair amount of refactoring that affected this, though I did not deliberately fix it. I cannot recreate it at the moment, however, even using a "register pack" execution inside a "packs.install".
