### ISSUE TITLE
Execution re-run doesn't display "Show Execution" button in the pop up whereas action run does

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2web#477]
(Sorry, too hard to take a screenshot)

**Comment by christopherjbaker** [comment]
I think this is working as intended. When you re-run an execution, it automatically navigates to the new execution (so no point in having a button).

**Comment by lakshmi-kannan** [comment]
I'll close this issue since we have established I am a noob!

Re-run does highlight the execution right. So "Show Execution" is not needed.
