### ISSUE TITLE
st2flow "+" button not hidden in action page in st2

### ISSUE THREAD

**Issue by humblearner** [StackStorm/st2web#487]
![image](https://user-images.githubusercontent.com/11877841/35238664-07278438-ff63-11e7-9413-e5cd7135c059.png)

and points to : `https://<IP>/undefined/#/import/eyJhdXRoIjp.....` in st2 community edition

**Comment by longfei-zhang** [comment]
I have this issue too.
https://forum.stackstorm.com/t/cant-create-new-action-in-actions-web-ui/90/3

**Comment by javierfigueroa** [comment]
@LindsayHill based on the answer from the forum, is this button not supposed to show unless you have the workflow composer installed? what is the current work around to add actions, use the CLI?
Thanks.

**Comment by LindsayHill** [comment]
Correct, it should only show if you have the st2flow package installed.
This is part of Workflow Composer.

You can add actions via API or CLI. See docs.stackstorm.com/actions.html

**Comment by LindsayHill** [comment]
Fixed in https://github.com/StackStorm/st2web/pull/570
