### ISSUE TITLE
Proposal: Remove Reamaze integration, add Forum.stackstorm.com

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2web#510]
Our new [forum](https://forum.stackstorm.com) is coming along nicely.

I think we should remove the Reamaze integration from st2web, and instead have a link to forum.stackstorm.com. 

I would like to do this in v2.7.

Thoughts?

**Comment by christopherjbaker** [comment]
Might be too much, but would probably be possible to integrate a small
search in a panel.

**Comment by LindsayHill** [comment]
That might work. MVP is just to link to forums, but if there's better integration, then we should look at it.

Main thing is that if we do something it doesn't block on systems that don't have direct Internet access.

**Comment by Kami** [comment]
:+1:  for integrating that into WebUI.

As long as it's unobtrusive integration (link is fine) - aka only loads on request or similar so discourse doesn't track every user...

**Comment by LindsayHill** [comment]
Resolved by #527
