### ISSUE TITLE
Filtering not applied upon history refresh

### ISSUE THREAD

**Issue by vincent-legoll** [StackStorm/st2web#513]
In history view, select a filter, then wait for some other (than those shown by the filter) actions to be run (maybe via triggers) those new executions are shown in the history view even if they should have been filtered out.

I am seeing a core.st2.CronTimer & a core.st2.webhook whereas I have the packs.install filter on.

**Comment by LindsayHill** [comment]
I've just tested this with 2.7.2, and current master (pre-release 2.8). I could reproduce it on 2.7.2, but not on 2.8-dev. 

Note that both st2web instances were pointing at the same underlying 2.7.2 ST2 system.

So this seems to be resolved, most likely by #530
