### ISSUE TITLE
Stale entries in 'action' filter entry

### ISSUE THREAD

**Issue by vincent-legoll** [StackStorm/st2web#514]
There are stale entries (from old deleted actions) in the 'action' filtering combobox.

How can I cleanup those ?

**Comment by LindsayHill** [comment]
Assuming you a referring to the Action filter on the History tab, that list comes from the execution history, not from the currently installed actions.

To remove those items, you'll need to [remove them from the execution history](https://docs.stackstorm.com/troubleshooting/purging_old_data.html).
