### ISSUE TITLE
Real time action output (streaming) in st2web

### ISSUE THREAD

**Issue by pietervogelaar** [StackStorm/st2web#516]
I run StackStorm 2.6.0. And configured in st2.conf `stream_output = True` within the actionrunner section. However I still only see action output in st2web when the action is completed.

Am I forgetting something? Or is real time stream output not supported yet in st2web?

**Comment by armab** [comment]
Not supported yet, but it's something we wanted to add to st2web as a feature cc @lakshmi-kannan 

Thanks for creating an issue for tracking this! :+1:

**Comment by pietervogelaar** [comment]
Okay, thanks for clearing that up. We have a patch action, that patches all servers of are data centers. It's running quite a long time, so it would be very very nice if we could see the real time output in the GUI.

**Comment by LindsayHill** [comment]
Check out https://github.com/StackStorm/st2web/pull/596 to see this in progress
