### ISSUE TITLE
How do I update README.md screenshots?

### ISSUE THREAD

**Issue by kaishuu0123** [StackStorm/st2web#528]
I want to update README.md screenshot.
but do not know upload place (https://cloud.githubusercontent.com/assets/1357357/7393040/010f78ac-eea5-11e4-82bf-8253674683e1.png)

Add a screenshot of the development environment I took

![2018-04-24 23 46 05](https://user-images.githubusercontent.com/1567423/40757218-6f4bf804-64c2-11e8-81db-4b0de4bc4633.png)

**Comment by enykeev** [comment]
I believe this is exactly what I did last time: created an issue, put a screenshot in there, copied the link and pasted it into Readme.md.

Thing is, we're not done restyling just yet. I was planning to update the screenshot right before the 2.8 release.

**Comment by kaishuu0123** [comment]
@enykeev 
Thank you for your comment!
I understand how to update. So I close this issue.

looking forward new st2web!

**Comment by bigmstone** [comment]
Most typical way I see would be a PR that contains the screen shots in the repo itself and then linking to them in the readme via relative path.
