### ISSUE TITLE
Cancel button on History tab seems unnecessary

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2web#559]
(2.8dev) On the History tab, if I click on an execution, I see this:

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/3607046/41567114-8b395dc2-7313-11e8-93ce-5d1af41e0f53.png">

Note the "Rerun" and "Cancel" buttons. There does not seem to be any situation where I can use that Cancel button. The only time it makes sense is if I click Rerun, and then click Cancel before execution. But clicking Rerun brings up a new box. 

This Cancel button _might_ make sense if I could edit parameters without having a separate popup.

**Comment by christopherjbaker** [comment]
When on a long-running execution, such as a workflow, the cancel button will be available.

**Comment by LindsayHill** [comment]
Good point. Maybe a tooltip makes sense? Will close this then

**Comment by christopherjbaker** [comment]
Might make sense to only show it when it is available, rather than disabling it? Thats probably a question for @adrifolio though.

**Comment by adrifolio** [comment]
I think it makes sense to show it only when is usable. Something else that would be beneficial is to show a loading icon on the rerun button while the workflow runs. For quick workflows it wouldn't make much of a difference, but for long workflows it would make the interaction more clear.
