### ISSUE TITLE
Login font uses serif font

### ISSUE THREAD

**Issue by blag** [StackStorm/st2web#651]
The login screen uses a serif font, but the fonts used in the rest of st2web are all sans serif fonts. This makes the login screen look a little weird:

<img width="272" alt="screen shot 2018-12-13 at 3 21 20 pm" src="https://user-images.githubusercontent.com/597113/49973724-12253c80-feeb-11e8-8eda-49555cda2896.png">

**Comment by m4dcoder** [comment]
Fixed at https://github.com/StackStorm/st2web/pull/656
