### ISSUE TITLE
Web UI not working 

### ISSUE THREAD

**Issue by sdmanal** [StackStorm/st2web#703]
I did the configuration as mentionned in the docs, 
The code is below: 

**config.js**
`
'use strict'
angular.module('main')
  .constant('st2config',{
hosts:[
{
name:'exple1',
url:'http://127.0.0.1:9101',
auth:'https://127.0.0.1:9100',
},
],
});
`
st2.conf 
`
[api]
host = 127.0.0.1
port = 9101
logging = /etc/st2/logging.api.gunicorn.conf
mask_secrets = True
allow_origin= http://127.0.0.1:3000
.
.
.
[auth]
host = 127.0.0.1
port = 9100
use_ssl = True 
logging = /etc/st2/logging.auth.gunicorn.conf 
mode = standalone 
backend = flat_file 
backend_kwargs = {"file_path":"/etc/st2/htpasswd"}
api_url = https://127.0.0.1:9101
.
.
.
[webui]
webui_base_url = https://localhost
`

with this configuration, i' can't access the web ui by typing 127.0.0.1:3000 in the browser's url field. Can you please help ? 
and also st2chatops is not working.

**Comment by LindsayHill** [comment]
You should just be using `https://<IP of your ST2 server>`

127.0.0.1:3000 is only if you are doing st2web development.

**Comment by sdmanal** [comment]
> You should just be using `https://<IP of your ST2 server>`
> 
> 127.0.0.1:3000 is only if you are doing st2web development.

In my case, is it 127.0.0.1:9101 ?
