### ISSUE TITLE
3.4 Dev - st2flow Errors selecting Tasks

### ISSUE THREAD

**Issue by jamesdreid** [StackStorm/st2web#855]
If the Packs.install workflow is loaded into ST2flow, clicking on certain tasks will cause the page to go blank and generate javascript errors in the Developer console.

On a brand new Centos8 install, clicking on the "stop_installation_and_cleanup_because_conflict" task as shown below:

![image](https://user-images.githubusercontent.com/6311944/106955618-17f9bf80-66fb-11eb-92ad-e840faeda6cb.png)

Blanks the Flow GUI and generates the following errors in the Dev Console:

![image](https://user-images.githubusercontent.com/6311944/106955828-6313d280-66fb-11eb-9946-32d366427db6.png)

Reloading the page will cause correct the GUI display but clicking on the task again will repeatedly fail.

Clicking on other tasks will also generate the same error (always) but I have not been able to identify something common that would identify which task would fail.

**Comment by jamesdreid** [comment]
It appears that the issue will only occur when the Task "Side Panel" is open.  Closing the panel will allow the task to be selected and moved but the error will be generated as soon as the panel is re-opened, assuming the failing task is still selected.

The image below shows the panel closed and the failing task selected:

![image](https://user-images.githubusercontent.com/6311944/106956734-a4f14880-66fc-11eb-90d7-3c2ac42ab103.png)

**Comment by amanda11** [comment]
Tested this on a 3.4dev system I have on CentOS 8 with Chrome browser. Had the same problem on that workflow.

However I've been using it on my own workflows successfully, so not sure what it is about the failing task...

Also replicated the same problem on the old EWC version of the composer, as I found that it occurred on a StackStorm 3.2 + EWC version I have on CentOS 7.
On the CentOS 7 one I briefly saw an error pop up stating that it couldn't find the action mentioned, and so did it exist - so I wonder if

**Comment by amanda11** [comment]
I'm seeing this on some of my workflows, and I think the common problem might be when it's an array parameter.

So in both my cases, and the example here, the problem occurs when the workflow calls a task that takes in an array parameter, and you pass say <% ctx().my_array_list %> to it.

**Comment by amanda11** [comment]
Also see https://github.com/StackStorm/st2/issues/5185#issuecomment-817136603 which mentions some other times that the blank screen appears
