### ISSUE TITLE
Workflow Composer Enhancement - Ctrl/Cmd Shortcuts

### ISSUE THREAD

**Issue by dylan-bitovi** [StackStorm/st2web#917]
When working in the Workflow Composer it would be nice if we could utilize universal shortcuts that exist within most editing programs.

`Ctrl/Cmd + S` to save would be of particular use to save the workflow rather than webpage itself similarly to how a page like diagrams.net is able to interpret this shortcut to raise their save a flowchart menu.

`Ctrl/Cmd + Z` to undo would be similarly handy. There exists some behavior for this when utilizing the raw code view, but even that text pane's behavior was inconsistent in my tests (e.g clicking away from the text pane seems to break undo history).

`Ctrl/Cmd + C/X/V` to copy/cut/paste existing objects and attached transitions would be useful for action modules or templates that are frequently re-used.

`Ctrl/Cmd + O` to open a workflow in a new workflow composer tab.

A command to run the execution would be helpful as well, but fairly minor.

I understand some of these are much more complex than others (e.g implementing an undo history record is likely more work than parsing a ctrl-s input) but all of them would be useful quality of life improvements for the composer.

**Comment by armab** [comment]
Thanks for the suggestions, these are definitely great ideas! :+1: 

We're open to contributions if someone wants to implement this nice functionality in the Workflow Designer.
