### ISSUE TITLE
Support on Web UI goes to deprecated forum.stackstorm.com

### ISSUE THREAD

**Issue by amanda11** [StackStorm/st2web#924]
With the move from Discourse Forum to GitHub discussions, then forum.stackstorm.com is a read-only version of the old forum. New issues are now raised in GitHub discussions.

Suggest that the Support link on the Web-UI is updated to go to https://github.com/StackStorm/st2/discussions instead of forum.stackstorm.com.

**Comment by armab** [comment]
`+100`  Good find!

**Comment by amanda11** [comment]
Resolved by https://github.com/StackStorm/st2web/pull/938
